### ISSUE TITLE
Error when files array is empty

### ISSUE THREAD

**Issue by tykarol** [DragonsInn/fontgen-loader#18]
When files array is empty then throw error in console:

Module build failed: Error: "options.files" is empty.
    at webfont (...\node_modules\webfonts-generator\src\index.js:49:41)
    at Object.module.exports (...\node_modules\fontgen-loader\index.js:155:5)

Probably fontgen-loader should check files array and if is empty do not run webfonts-generator.

**Comment by MeishanGuo** [comment]
i also met this problem
